// this file is generated by resource_list.py
#include <unordered_map>
#include "resource_provider.h"

namespace resource {
    const std::unordered_map<const char *, GroundInfo> GROUNDS_LIST = {
        {"grounds/grass", { 256, 1, 256 }},
        {"grounds/small", { 1, 1, 1 }},
        {"grounds/white", { 64, 1, 64 }},
    };
}
