// this file is generated by resource_list.py
#include <unordered_map>
#include "resource_provider.h"

namespace resource {
    const std::unordered_map<const char *, MeshInfo> MESHES_LIST = {
        {"meshes/stool", { 5, 6, 5 }},
        {"meshes/test/ruins", { 40, 20, 40 }},
        {"meshes/test/pillon", { 8, 20, 8 }},
        {"meshes/test/tree", { 8, 17, 8 }},
    };
}
