// this file is generated by resource_list.py
#include <unordered_map>
#include "mesh_provider.h"

namespace resource {
    const std::unordered_map<const char *, MeshInfo> MESHES_LIST = {
        {"actors/knight", { 7, 8, 7 }},
        {"things/pillar", { 4, 10, 4 }},
        {"things/table", { 8, 3, 5 }},
        {"things/books", { 3, 10, 9 }},
    };
}
