// this file is generated by resource_list.py
#include <unordered_map>
#include "place_provider.h"

namespace resource {
    const std::unordered_map<const char *, PlaceInfo> PLACES_LIST = {
        {"places/floor", { 64, 1, 64 }},
    };
}
