// this file is generated by resource_list.py
#include <unordered_map>

namespace resource {
    const std::unordered_map<const char *, MeshInfo> MESHES_LIST = {
        {"meshes/a-knight-blue", { 15, 187, 1835626081 }},
        {"meshes/a-knight-red", { 15, 187, 1835626081 }},
        {"meshes/castle-00", { 50, 60, 1835626081 }},
        {"meshes/castle-01", { 62, 60, 1835626081 }},
        {"meshes/b-tavern-0", { 13, 58, 1835626081 }},
        {"meshes/ruins", { 64, 1, 256 }},
        {"meshes/b-bows-0", { 15, 58, 1835626081 }},
        {"meshes/b-blacksmith-0", { 12, 58, 1835626081 }},
        {"meshes/voxtest", { 3, 1, 256 }},
        {"meshes/1x1x1", { 1, 1, 256 }},
    };
}
namespace resource {
    const std::unordered_map<const char *, TextureInfo> TEXTURES_LIST = {
        { "textures/misc/green", { 16, 16, foundation::RenderTextureFormat::RGBA8UN }},
        { "textures/ui/joystick_bg", { 248, 248, foundation::RenderTextureFormat::RGBA8UN }},
        { "textures/ui/button_down", { 100, 40, foundation::RenderTextureFormat::RGBA8UN }},
        { "textures/ui/joystick_thumb", { 77, 77, foundation::RenderTextureFormat::RGBA8UN }},
        { "textures/ui/img9slice", { 128, 128, foundation::RenderTextureFormat::RGBA8UN }},
        { "textures/ui/button_up", { 100, 40, foundation::RenderTextureFormat::RGBA8UN }},
        { "textures/ui/btn_slice_press", { 32, 32, foundation::RenderTextureFormat::RGBA8UN }},
        { "textures/ui/joystick_bg_00", { 256, 256, foundation::RenderTextureFormat::RGBA8UN }},
        { "textures/ui/joystick_st_00", { 96, 96, foundation::RenderTextureFormat::RGBA8UN }},
        { "textures/ui/btn_circle_down", { 64, 64, foundation::RenderTextureFormat::RGBA8UN }},
        { "textures/ui/btn_circle_up", { 64, 64, foundation::RenderTextureFormat::RGBA8UN }},
        { "textures/ui/btn_slice_base", { 32, 32, foundation::RenderTextureFormat::RGBA8UN }},
        { "textures/particles/test", { 32, 32, foundation::RenderTextureFormat::RGBA8UN }},
    };
}
namespace resource {
    const std::unordered_map<const char *, GroundInfo> GROUNDS_LIST = {
    };
}
