// this file is generated by resource_list.py
#include <unordered_map>
#include "texture_provider.h"

namespace resource {
    const std::unordered_map<const char *, TextureInfo> TEXTURES_LIST = {
        { "ui/joystick_bg", { 248, 248, TextureInfo::Type::RGBA8 }},
        { "ui/button_down", { 100, 40, TextureInfo::Type::RGBA8 }},
        { "ui/joystick_thumb", { 77, 77, TextureInfo::Type::RGBA8 }},
        { "ui/button_up", { 100, 40, TextureInfo::Type::RGBA8 }},
        { "ui/panel", { 358, 358, TextureInfo::Type::RGBA8 }},
        { "ui/btn_square_down", { 96, 96, TextureInfo::Type::RGBA8 }},
        { "ui/joystick_bg_00", { 256, 256, TextureInfo::Type::RGBA8 }},
        { "ui/joystick_st_00", { 96, 96, TextureInfo::Type::RGBA8 }},
        { "ui/btn_circle_down", { 64, 64, TextureInfo::Type::RGBA8 }},
        { "ui/btn_circle_up", { 64, 64, TextureInfo::Type::RGBA8 }},
        { "ui/btn_square_up", { 96, 96, TextureInfo::Type::RGBA8 }},
        { "steads/floor_00", { 72, 64, TextureInfo::Type::RGBA8 }},
    };
}
