// this file is generated by resource_list.py
#include <unordered_map>
#include "resource_provider.h"

namespace resource {
    const std::unordered_map<const char *, TextureInfo> TEXTURES_LIST = {
        { "textures/ui/joystick_bg", { 248, 248, foundation::RenderTextureFormat::RGBA8UN }},
        { "textures/ui/button_down", { 100, 40, foundation::RenderTextureFormat::RGBA8UN }},
        { "textures/ui/joystick_thumb", { 77, 77, foundation::RenderTextureFormat::RGBA8UN }},
        { "textures/ui/button_up", { 100, 40, foundation::RenderTextureFormat::RGBA8UN }},
        { "textures/ui/panel", { 358, 358, foundation::RenderTextureFormat::RGBA8UN }},
        { "textures/ui/btn_square_down", { 96, 96, foundation::RenderTextureFormat::RGBA8UN }},
        { "textures/ui/joystick_bg_00", { 256, 256, foundation::RenderTextureFormat::RGBA8UN }},
        { "textures/ui/joystick_st_00", { 96, 96, foundation::RenderTextureFormat::RGBA8UN }},
        { "textures/ui/btn_circle_down", { 64, 64, foundation::RenderTextureFormat::RGBA8UN }},
        { "textures/ui/btn_circle_up", { 64, 64, foundation::RenderTextureFormat::RGBA8UN }},
        { "textures/ui/btn_square_up", { 96, 96, foundation::RenderTextureFormat::RGBA8UN }},
        { "textures/particles/test", { 32, 32, foundation::RenderTextureFormat::RGBA8UN }},
    };
}
