
set(CMAKE_SYSTEM_NAME iOS)

set(CMAKE_CXX_COMPILER_WORKS TRUE)
set(CMAKE_C_COMPILER_WORKS TRUE)
#set(CMAKE_OSX_ARCHITECTURES "arm64;x86_64")
set(CMAKE_MACOSX_BUNDLE YES)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY )

set(CMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH "YES")
set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD "c++17")
set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_LIBRARY "libc++")
set(CMAKE_XCODE_ATTRIBUTE_ENABLE_BITCODE "YES")
set(CMAKE_XCODE_ATTRIBUTE_SKIP_INSTALL "NO")
