
set(CMAKE_SYSTEM_NAME iOS)

set(CMAKE_CXX_COMPILER_WORKS TRUE)
set(CMAKE_C_COMPILER_WORKS TRUE)
set(CMAKE_OSX_ARCHITECTURES "arm64;x86_64")
set(CMAKE_MACOSX_BUNDLE YES)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY )

set(CMAKE_XCODE_ATTRIBUTE_ONLY_ACTIVE_ARCH "YES")
set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_STANDARD "c++20")
set(CMAKE_XCODE_ATTRIBUTE_CLANG_CXX_LANGUAGE_LIBRARY "libc++")
set(CMAKE_XCODE_ATTRIBUTE_SKIP_INSTALL "NO")
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_IDENTITY "Apple Development")
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGN_STYLE "Automatic")
set(CMAKE_XCODE_ATTRIBUTE_CODE_SIGNING_REQUIRED "NO")
set(CMAKE_XCODE_ATTRIBUTE_DEVELOPMENT_TEAM "")

set(CMAKE_OSX_DEPLOYMENT_TARGET "13.2")

